"""cs architecture refactoring

Revision ID: 49e6a378ad1c
Revises: 0001
Create Date: 2026-06-23 15:56:44.345320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49e6a378ad1c'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('host_configs', sa.Column('last_heartbeat', sa.DateTime(), nullable=True, comment='Agent 最后心跳时间'))
    op.add_column('host_configs', sa.Column('agent_version', sa.String(length=50), nullable=True, comment='Agent 版本号'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('host_configs', 'agent_version')
    op.drop_column('host_configs', 'last_heartbeat')
    # ### end Alembic commands ###
