"""add mysql_path

Revision ID: b0ac3221930c
Revises: cd46c6ae8565
Create Date: 2026-07-01 12:02:21.147557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0ac3221930c'
down_revision: Union[str, None] = 'cd46c6ae8565'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('host_configs', sa.Column('mysql_path', sa.String(length=255), nullable=False, comment='MySQL可执行文件路径'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('host_configs', 'mysql_path')
    # ### end Alembic commands ###
