"""add_direct_nfs

Revision ID: cd46c6ae8565
Revises: 49e6a378ad1c
Create Date: 2026-06-29 16:49:52.059159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd46c6ae8565'
down_revision: Union[str, None] = '49e6a378ad1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('host_configs', sa.Column('direct_nfs', sa.Boolean(), nullable=False, comment='是否启用直写 NFS 模式'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('host_configs', 'direct_nfs')
    # ### end Alembic commands ###
